##All credit goes to Awesome__Luke

##Format of the staff chat in the chat. & color codes are accepted.
format: '&c[SC] %player%: %message%'

##Prefix to use the staff chat without /sc. Ex: #hello
chatprefix: '#'

##Message to send if player doesn't have permission
no-permission-message: '&c[SC] No permission bald man!'

##Message to send if the message doesn't have any content
not-enough-args: '&c[SC] Not enough arguments.'